### ISSUE TITLE
memery leak for deno_bindgen

### ISSUE THREAD

**Issue by usrtax** [denoland/deno_bindgen#108]
deno 1.26.0 (release, x86_64-unknown-linux-gnu)
v8 10.7.193.3
typescript 4.8.3

code is there https://github.com/usrtax/deno_bindgen_test

```
use deno_bindgen::deno_bindgen;

#[deno_bindgen]
fn add3() -> &'static [u8] {
    &[
        1, 2, 3, 4, 5, 6, 7, 9, 0, 1, 2, 3, 4, 5, 6, 7, 9, 0, 1, 2, 3, 4, 5, 6, 7, 9, 0, 1, 2, 3,
    ]
}
```

test code https://github.com/usrtax/deno_bindgen_test/blob/main/lib/test.js

```
#!/usr/bin/env -S node --es-module-specifier-resolution=node --trace-uncaught --expose-gc --unhandled-rejections=strict
var main, n, sleep;

import {
  add3
} from '../bindings/bindings.ts';

sleep = () => {
  return new Promise((resolve) => {
    return setTimeout(resolve, 10);
  });
};

n = 0;

while (true) {
  main();
  if (n++ % 10000 === 0) {
    gc();
    await sleep();
    console.log(n, Deno.memoryUsage());
  }
}

```

run as begin
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110233389/193037795-edd3a14f-2df8-465c-bc9d-e3b201fc0564.png">

run 3mintues RES 1040M
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110233389/193038354-8d97c36b-bc1e-4e92-8346-d2a6a9592eed.png">

run 10minutes RES 2177M

run 1hour RES 14.9G
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110233389/193050195-70dc6fe9-708f-432f-8d46-7fefce80b454.png">

Deno.memoryUsage doesn't seem to be very accurate, pay more attention to the memory usage in top

**Comment by ar37-rs** [comment]
You are doing 'static stuff, any 'static stuff won't be dropped or freed until the application successfully exited.

**Comment by usrtax** [comment]
I change code into 
```
#[deno_bindgen]
fn add3(a: u64, b: u64) -> u64 {
    a + b
}
```

memery still leak

**Comment by littledivy** [comment]
Thanks for the report. This is a known issue, deno_bindgen leaks the buffer to JS land. The JS bindings should register a finalization callback to free the buffer.
