### ISSUE TITLE
Argument of type 'bigint' is not assignable to parameter of type 'PointerObject'.deno-ts(2345)

### ISSUE THREAD

**Issue by denizdogan** [denoland/deno_bindgen#119]
```console
$ deno --version
deno 1.31.1 (release, aarch64-apple-darwin)
v8 11.0.226.13
typescript 4.9.4
```

Error appears here:

```ts
function readPointer(v: any): Uint8Array {
  const ptr = new Deno.UnsafePointerView(v as bigint) // <-- here
```

I'm just assuming it's because of this change:

https://deno.com/blog/v1.31#breaking-change-in-ffi-api

**Comment by denizdogan** [comment]
Looks like PR's #117 and #118 address this issue. I'll leave the issue up until one of them gets merged.

**Comment by lino-levan** [comment]
#118 was closed, I believe this should be closed as well
