### ISSUE TITLE
Problem with struct params

### ISSUE THREAD

**Issue by kakashi-69-xd** [denoland/deno_bindgen#127]
#[deno_bindgen]
pub struct Inp {
  x: i8,
  y: i8
}

#[deno_bindgen]
pub fn xd(v: Inp)-> i8 {
  v.x+v.y
}
/*compiler says...
custom attribute panicked
message: Type defination not found for `Inp` identifier
.......and same goes for vectors

*/

**Comment by tristan-zander** [comment]
@kakashi-69-xd Hey, I recently ran into this issue as well. What operating system are you on? This is only a brief investigation, but it seems like it doesn't work on my OSX x64 machine, but does work on my GNU+Linux x64 machine. It _could_ be tied to the operating system in some way.

**Comment by kakashi-69-xd** [comment]
it was on windows.. Linux is fine..xd
