### ISSUE TITLE
Embedding deno in rust application

### ISSUE THREAD

**Issue by nearest-river** [denoland/deno_bindgen#141]
Can I embed the whole `deno` runtime in a rust app?.. not only `deno_core` which'll need all sorts of configurations like permission passing and things like command line arguments..

# NOTE: Making a build tool

**Comment by littledivy** [comment]
deno_bindgen is for writing FFI plugins, not for embedding Deno into Rust applications. Take a look at deno_runtime https://github.com/denoland/deno/tree/main/runtime

Issues related to embedding should be opened in `denoland/deno`

**Comment by nearest-river** [comment]
> deno_bindgen is for writing FFI plugins, not for embedding Deno into Rust applications. Take a look at deno_runtime https://github.com/denoland/deno/tree/main/runtime
> 
> Issues related to embedding should be opened in `denoland/deno`

I accidentally issued it in deno_bindgen repo
