### ISSUE TITLE
Pluggable serialization

### ISSUE THREAD

**Issue by rracariu** [denoland/deno_bindgen#23]
Having an option to override the default JSON serialization would be nice.

For example the https://github.com/Adelost/javascript-serialization-benchmark list other more performant options such as AVRO.

**Comment by eliassjogreen** [comment]
My module [byte_type](https://deno.land/x/byte_type@0.1.7) now supports some simple [ffi](https://deno.land/x/byte_type@0.1.7/ffi.ts) serialization which may help.

**Comment by wobsoriano** [comment]
> My module [byte_type](https://deno.land/x/byte_type@0.1.7) now supports some simple [ffi](https://deno.land/x/byte_type@0.1.7/ffi.ts) serialization which may help.

Is there a sample usage of it where we can pass structs, arrays?

**Comment by wobsoriano** [comment]
> My module [byte_type](https://deno.land/x/byte_type@0.1.7) now supports some simple [ffi](https://deno.land/x/byte_type@0.1.7/ffi.ts) serialization which may help.

Hi! Do you have any examples of how to read pointers using your module? I am able to write, just not read from returned structs. Thanks!
