### ISSUE TITLE
support `&str` as a return type

### ISSUE THREAD

**Issue by mwcz** [denoland/deno_bindgen#53]
`&str` is already accepted as a parameter type, but it would be nice 🌠 to be able to return a `&str`. (Thanks to Andreu and divy for help in the discord.)

Here's an example of a `&str` param from the 0.2 release announcement:
```rust
#[deno_bindgen]
pub fn say_hello(message: &str)  {
    println!("{}", message);
}
```

If it's changed to return a `&str` instead of printing it...

```rust
#[deno_bindgen]
pub fn say_hello(message: &str) -> &str {
    format!("{}", message)
}
```

The result is:
```rust
error: custom attribute panicked  
 --> src/lib.rs:5:1               
  |                               
5 | #[deno_bindgen]               
  | ^^^^^^^^^^^^^^^               
  |                               
  = help: message: not implemented
```

That's from the current version of deno_bindgen, 0.5.

This would be a really nice feature to have and would allow easily passing text across the FFI boundary.

**Comment by fourtf** [comment]
Wouldn't returning `&str` cause ownership issues unless the lifetime is `'static`?

**Comment by littledivy** [comment]
> Wouldn't returning `&str` cause ownership issues unless the lifetime is `'static`?

Ideally, the data will be leaked to JS land and the pointer will be deallocated back in Rust land using JS finalization callbacks.

**Comment by lucacasonato** [comment]
@mwcz Am I understanding you correctly in that you want to return a string from the function? Why does it need to be a borrowed `str`? An owned `String` seems much safer and more logical.

**Comment by mwcz** [comment]
@lucacasonato In the discord chat that led to this issue I did ask about `String`.  @littledivy explained:

> deno_bindgen does not accept owned String types because they create a false sense of ownership, because the string is actually copied. &str is not a copy

**Comment by littledivy** [comment]
@mwcz That explanation was in context of owned String in parameter types.
Returned values should ideally be owned values like `String` because deno_bindgen leaks these values to JS. So the explanation is quite opposite for return types :-)

**Comment by littledivy** [comment]
Returning owned strings are now supported on `main`:
```rust
#[deno_bindgen]
fn hello() -> String {
  String::from("🦕")
} 
```

**Comment by mwcz** [comment]
> @mwcz That explanation was in context of `&str` in parameter types. Returned values should ideally be owned values like `String` because deno_bindgen leaks these values to JS. So the explanation is quite opposite for return types :-)


I see! Thank you for the explanation.

**Comment by andreubotella** [comment]
I think it still does make sense to allow returning `&'static str` or `str` references with the lifetime of one of the parameters.
