### ISSUE TITLE
Add // @ts-ignore above UnsafePointerView 

### ISSUE THREAD

**Issue by felipetesc** [denoland/deno_bindgen#62]
Hi, I wanted to know if it is possible to automatically add // @ts-ignore above UnsafePointerView to prevent VSCode and other editors to show: ```Property 'UnsafePointerView' does not exist on type 'typeof Deno'.deno-ts(2339):``` 
Like this:
```typescript
// @ts-ignore
  const ptr = new Deno.UnsafePointerView(v as Deno.UnsafePointer)
```
At least until the API can be stabilized. 
By the way, really nice job. Already tested winit.
Thanks.

**Comment by littledivy** [comment]
`Deno.UnsafePointerView` is behind the `--unstable` flag. Have you enabled `deno.unstable` in vscode? Like so:

`.vscode/settings.json`:
```json
{
  "deno.enable": true,
  "deno.unstable": true
}
```
