### ISSUE TITLE
Accessing structs from C to Deno

### ISSUE THREAD

**Issue by walmartwarlord** [denoland/deno_bindgen#69]
Hello, I know this is a rust based codegen but I hope it's ok to ask this. What could be the best way to access structs that contains strings in Deno from C? Is it advisable just to stringify the object in C so that I can do `new Deno.UnsafePointerView(ptr).getCString()` in Deno?

Example

```h
typedef struct { char name; int age; } SampleObject;
```

**Comment by littledivy** [comment]
Consider using https://deno.land/x/byte_type for that.

```typescript
import { Struct, u8, isize } from "https://deno.land/x/byte_type/ffi.ts";

const SampleObject = new Struct({
  name: u8,
  age: isize,
});

const ptr = lib.symbols.asd();
const view = new Deno.UnsafePointerView(ptr);
const object = SampleObject.read(view);
```

**Comment by walmartwarlord** [comment]
Closing this. Using [byte_type](https://deno.land/x/byte_type@0.1.7) works .
