### ISSUE TITLE
Bug: Program crash after deno_bindgen rebuild

### ISSUE THREAD

**Issue by kayac-chang** [denoland/deno_bindgen#75]
### OS: 
MacOS Monterey version 12.4

### Hardware:
  Model Name:	MacBook Pro
  Chip:	Apple M1
  Memory:	16 GB

## Steps To Reproduce

1. first run `deno_bindgen` to build first `ffi`
2. run `deno run --allow-all --unstable main.ts`, we can get `Hello, world` print out
3. update `src/lib.rs` source code, like change `Hello, world` to `Hello, kirby`
4. run `deno_bindgen` again
5. run `deno run --allow-all --unstable main.ts` will crash without any error

```bash
$ deno run --allow-all --unstable main.ts                                                                                                                
[1]    11128 killed     deno run --allow-all --unstable main.ts
```

Link to code example:
https://github.com/kayac-chang/test-deno-bindgen

## Problem 
I think because of [this line](https://github.com/denosaurs/plug/blob/main/plug.ts#L96),
but I don't know the reason why need to use system cache,
because there's no useful document to point out intention.

## Temporary Solution
Currently, I fork [plug](https://github.com/denosaurs/plug) 
and add the following code to skip the cache, 
this will solve the issue temporarily.

```ts
  ...

  if (options.policy === CachePolicy.NONE) {
    return new URL(url).pathname;
  }

  const file = await plug.cache(url, policy);

  return file.path;
}
```

**Comment by skanehira** [comment]
I'm facing this problem too.
When cache policy is `NONE`, `x/cache` will always copy `./target/debug/*.lib` to cache directory.
So the lib in cache will always have a new but `Deno.dlpopen` didn't work.
