### ISSUE TITLE
Publish new release/tag for Deno 1.24.1

### ISSUE THREAD

**Issue by zifeo** [denoland/deno_bindgen#86]
Happy to help as maintainer/releaser if there is too much to make elsewhere.

**Comment by littledivy** [comment]
I'll cut a release right after Deno 1.25 is released tommorow. There is one breaking change in the FFI API.

**Comment by minioin** [comment]
Hey @littledivy, any idea on when this might be released?

**Comment by littledivy** [comment]
https://github.com/denoland/deno_bindgen/releases/tag/0.7.0

**Comment by littledivy** [comment]
Sorry for the delay
