### ISSUE TITLE
deno_bindgen = "0.6.0": message: Type definition not found for `f32` identifier

### ISSUE THREAD

**Issue by usrtax** [denoland/deno_bindgen#94]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110233389/189660560-e1887ac5-3c9f-4f8e-80f8-a2e293c6d824.png">

error: custom attribute panicked
 --> src/lib.rs:5:1
  |
5 | #[deno_bindgen]
  | ^^^^^^^^^^^^^^^
  |
  = help: message: Type definition not found for `f32` identifier

**Comment by skanehira** [comment]
Seems like f32 missing.
I think we should add.

https://github.com/denoland/deno_bindgen/blob/095e88d35e3b30167917b60de1fd2f17e02d68d6/deno_bindgen_macro/src/derive_fn.rs#L30-L41

**Comment by skanehira** [comment]
I'll fix this

**Comment by farshed** [comment]
Hi, any idea when the next release will be? Could really use this floating type support

**Comment by bartlomieju** [comment]
@littledivy could you cut a release?
